version: "3"
services:
  lampoai:
    image: # IMAGE STORAGE, with container_name
    build:
      context: .
    container_name: # container_name
    env_file: .env
    environment:
      NEXT_PUBLIC_APP_URL: 'http://localhost:3000'
    restart: always
    ports:
      - 3000:3000